// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBawNv_KWuk5OAFJKRWVBpzjnzxbjz-sx4',
    appId: '1:595160262693:web:400fe3c75b0f87b8e7f7cc',
    messagingSenderId: '595160262693',
    projectId: 'notificationtemplate-f0f84',
    authDomain: 'notificationtemplate-f0f84.firebaseapp.com',
    storageBucket: 'notificationtemplate-f0f84.appspot.com',
    measurementId: 'G-E3G5F3FZ0Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWP4zUkub_p0Ec_fwDFiWuZPOyCAlKNiY',
    appId: '1:595160262693:android:cb6824a9017266ede7f7cc',
    messagingSenderId: '595160262693',
    projectId: 'notificationtemplate-f0f84',
    storageBucket: 'notificationtemplate-f0f84.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHuVp1_K0aZBMSRK9RKxpROR-mJA9c3eQ',
    appId: '1:595160262693:ios:5ebb54d703c6d083e7f7cc',
    messagingSenderId: '595160262693',
    projectId: 'notificationtemplate-f0f84',
    storageBucket: 'notificationtemplate-f0f84.appspot.com',
    iosBundleId: 'com.example.notificationtemplate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHuVp1_K0aZBMSRK9RKxpROR-mJA9c3eQ',
    appId: '1:595160262693:ios:902f241bbf122e68e7f7cc',
    messagingSenderId: '595160262693',
    projectId: 'notificationtemplate-f0f84',
    storageBucket: 'notificationtemplate-f0f84.appspot.com',
    iosBundleId: 'com.example.notificationtemplate.RunnerTests',
  );
}
